
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploymentpipeline-config
  namespace: replaceme
data:
  spring.datasource.url: replaceme
  spring.datasource.username: replaceme
  spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
  logbackpath: /etc/config/logback.xml
  logback.xml: |
     <configuration scan="true" scanPeriod="3 seconds" debug="false"><statusListener class="ch.qos.logback.core.status.NopStatusListener" />	<property resource="application.properties" /><property name="namespace" value="${kubernetes.namespace}"></property><property name="defaultPattern"	value="%d{yyyy-MM-dd HH:mm:ss.SSS} $ threadId: {PID:- } %-5level  namespace:replaceme %logger{20} [ hostname: %X{hostname} serviceName: %X{serviceName} version: %X{version} transactionId: %X{transactionId} requestTimeStamp: %X{requestTimestamp}  responseTimeStamp: %X{responseTimestamp} duration: %X{duration}] %m%n" />	<property name="performanceandAuditpattern" value="%date{ISO8601,UTC}|%thread|%.-5level|namespace:replaceme|%logger{20}|%X{ServerIPAddress}|%X{ServerFQDN}|%X{serviceName}| %msg%n" />	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">		<encoder>			<pattern>${defaultPattern}</pattern>		</encoder>	</appender>	<appender name="performanceandAudit" class="ch.qos.logback.core.ConsoleAppender">		<encoder>			<pattern>${performanceandAuditpattern}</pattern>		</encoder>	</appender>	<logger name="com.att.eelf.perf" level="INFO">		<appender-ref ref="performanceandAudit" />	</logger>	<logger name="com.att.eelf.audit" level="DEBUG">		<appender-ref ref="performanceandAudit" />	</logger>	<logger name="com.att.ajsc" level="INFO" />	<root level="INFO">		<appender-ref ref="STDOUT" />	</root></configuration>
  AAFUserRoles.properties: |
    /TestAafRc3/v1/jaxrsExample/**=com.att.ajsc.security|demo|admin
    /TestAafRc3/v1/helloWorld=com.att.ajsc.security|demo|access
    /camunda/Application/*=com.att.ajsc.camunda.application|Camunda_DEV|ALL
    /camunda/USER/*=com.att.ajsc.camunda.user|Camunda_DEV|ALL
    /camunda/GROUP/*=com.att.ajsc.camunda.group|Camunda_DEV|ALL
    /camunda/AUTHORIZATION/*=com.att.ajsc.camunda.authorization|Camunda_DEV|ALL
    /camunda/GROUP_MEMBERSHIP/*=com.att.ajsc.camunda.group_membership|Camunda_DEV|ALL
    /camunda/FILTER/*=com.att.ajsc.camunda.filter|Camunda_DEV|ALL
    /camunda/PROCESS_DEFINITION/*=com.att.ajsc.camunda.process_definition|Camunda_DEV|ALL
    /camunda/TASK/*=com.att.ajsc.camunda.task|Camunda_DEV|ALL
    /camunda/PROCESS_INSTANCE/*=com.att.ajsc.camunda.process_instance|Camunda_DEV|ALL
    /camunda/DEPLOYMENT/*=com.att.ajsc.camunda.deployment|Camunda_DEV|ALL
    AAFENABLEDPROP=FALSE
  cadi.properties:  |
    csp_devl_localhost=true
    basic_warn=TRUE
    cadi_loglevel=WARN
    cadi_keyfile=etc/aafkeystore/keyfile
    #cadi_keyfile=src/main/resources/keyfile
    # Configure AAF
    aaf_url=replaceme
    aaf_id=replaceme
    aaf_password=replaceme
    aaf_timeout=50000
    aaf_clean_interval=30000
    aaf_user_expires=5000
    aaf_high_count=1000
    